FROM nginx:stable-alpine

#COPY ./fullchain.pem /etc/letsencrypt/live/derisk-starknet-proxy-quichvtmsq-ew.a.run.app/
#COPY ./privkey.pem /etc/letsencrypt/live/derisk-starknet-proxy-quichvtmsq-ew.a.run.app/
COPY ./default.conf /etc/nginx/conf.d/default.conf
