"""migration for BearingCollateralBurnEventModel and DebtTransferEventModel

Revision ID: 163f616930fb
Revises: d3691f6e8c5a
Create Date: 2024-11-25 15:42:21.851978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from shared.constants import ProtocolIDs


# revision identifiers, used by Alembic.
revision: str = '163f616930fb'
down_revision: Union[str, None] = 'd3691f6e8c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bearing_collateral_burn_event',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs, impl=sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bearing_collateral_burn_event_block_number'), 'bearing_collateral_burn_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_bearing_collateral_burn_event_event_name'), 'bearing_collateral_burn_event', ['event_name'], unique=False)
    op.create_table('debt_burn_event',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs, impl=sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_burn_event_block_number'), 'debt_burn_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_debt_burn_event_event_name'), 'debt_burn_event', ['event_name'], unique=False)
    op.create_table('debt_mint_event',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs, impl=sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_mint_event_block_number'), 'debt_mint_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_debt_mint_event_event_name'), 'debt_mint_event', ['event_name'], unique=False)
    op.create_table('debt_transfer_event',
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs, impl=sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_transfer_event_block_number'), 'debt_transfer_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_debt_transfer_event_event_name'), 'debt_transfer_event', ['event_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debt_transfer_event_event_name'), table_name='debt_transfer_event')
    op.drop_index(op.f('ix_debt_transfer_event_block_number'), table_name='debt_transfer_event')
    op.drop_table('debt_transfer_event')
    op.drop_index(op.f('ix_debt_mint_event_event_name'), table_name='debt_mint_event')
    op.drop_index(op.f('ix_debt_mint_event_block_number'), table_name='debt_mint_event')
    op.drop_table('debt_mint_event')
    op.drop_index(op.f('ix_debt_burn_event_event_name'), table_name='debt_burn_event')
    op.drop_index(op.f('ix_debt_burn_event_block_number'), table_name='debt_burn_event')
    op.drop_table('debt_burn_event')
    op.drop_index(op.f('ix_bearing_collateral_burn_event_event_name'), table_name='bearing_collateral_burn_event')
    op.drop_index(op.f('ix_bearing_collateral_burn_event_block_number'), table_name='bearing_collateral_burn_event')
    op.drop_table('bearing_collateral_burn_event')
    # ### end Alembic commands ###
