"""interest rate and bearing mint

Revision ID: 80e10a0a5974
Revises: 163f616930fb
Create Date: 2024-11-26 15:25:50.890716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e10a0a5974'
down_revision: Union[str, None] = '163f616930fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accumulators_sync_event',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('lending_accumulator', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('debt_accumulator', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accumulators_sync_event_block_number'), 'accumulators_sync_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_accumulators_sync_event_event_name'), 'accumulators_sync_event', ['event_name'], unique=False)
    op.create_table('borrowing_event',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('raw_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('face_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowing_event_block_number'), 'borrowing_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_borrowing_event_event_name'), 'borrowing_event', ['event_name'], unique=False)
    op.create_table('collateral_enabled_disabled_event',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collateral_enabled_disabled_event_block_number'), 'collateral_enabled_disabled_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_collateral_enabled_disabled_event_event_name'), 'collateral_enabled_disabled_event', ['event_name'], unique=False)
    op.create_table('deposit_event',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('face_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_event_block_number'), 'deposit_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_deposit_event_event_name'), 'deposit_event', ['event_name'], unique=False)
    op.create_table('hashtack_collateral_debt',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('collateral', sa.JSON(), nullable=True),
    sa.Column('debt', sa.JSON(), nullable=True),
    sa.Column('debt_category', sa.Integer(), nullable=False),
    sa.Column('original_collateral', sa.JSON(), nullable=False),
    sa.Column('borrowed_collateral', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtack_collateral_debt_user_id'), 'hashtack_collateral_debt', ['user_id'], unique=False)
    op.create_index(op.f('ix_hashtack_collateral_debt_version'), 'hashtack_collateral_debt', ['version'], unique=False)
    op.create_table('health_ratio_level',
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('value', sa.DECIMAL(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_ratio_level_timestamp'), 'health_ratio_level', ['timestamp'], unique=False)
    op.create_index(op.f('ix_health_ratio_level_user_id'), 'health_ratio_level', ['user_id'], unique=False)
    op.create_table('interest_rate',
    sa.Column('block', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('collateral', sa.JSON(), nullable=True),
    sa.Column('debt', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_rate_block'), 'interest_rate', ['block'], unique=False)
    op.create_index(op.f('ix_interest_rate_timestamp'), 'interest_rate', ['timestamp'], unique=False)
    op.create_table('liquidable_debt',
    sa.Column('liquidable_debt', sa.DECIMAL(), nullable=False),
    sa.Column('protocol_name', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('collateral_token_price', sa.DECIMAL(), nullable=False),
    sa.Column('collateral_token', sa.String(), nullable=False),
    sa.Column('debt_token', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidation_event',
    sa.Column('liquidator', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('debt_token', sa.String(), nullable=False),
    sa.Column('debt_raw_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('debt_face_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('collateral_token', sa.String(), nullable=False),
    sa.Column('collateral_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidation_event_block_number'), 'liquidation_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_liquidation_event_event_name'), 'liquidation_event', ['event_name'], unique=False)
    op.create_table('loan_state',
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('deposit', sa.JSON(), nullable=True),
    sa.Column('block', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('collateral', sa.JSON(), nullable=True),
    sa.Column('debt', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'user', name='loan_state_protocol_id_user_key')
    )
    op.create_index(op.f('ix_loan_state_block'), 'loan_state', ['block'], unique=False)
    op.create_index(op.f('ix_loan_state_timestamp'), 'loan_state', ['timestamp'], unique=False)
    op.create_index(op.f('ix_loan_state_user'), 'loan_state', ['user'], unique=False)
    op.create_table('orderbook',
    sa.Column('token_a', sa.String(), nullable=False),
    sa.Column('token_b', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('block', sa.BigInteger(), nullable=False),
    sa.Column('dex', sa.String(), nullable=False),
    sa.Column('current_price', sa.DECIMAL(), nullable=True),
    sa.Column('asks', sa.JSON(), nullable=True),
    sa.Column('bids', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderbook_dex'), 'orderbook', ['dex'], unique=False)
    op.create_index(op.f('ix_orderbook_token_a'), 'orderbook', ['token_a'], unique=False)
    op.create_index(op.f('ix_orderbook_token_b'), 'orderbook', ['token_b'], unique=False)
    op.create_table('repayment_event',
    sa.Column('repayer', sa.String(), nullable=False),
    sa.Column('beneficiary', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('raw_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('face_amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayment_event_block_number'), 'repayment_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_repayment_event_event_name'), 'repayment_event', ['event_name'], unique=False)
    op.create_table('withdrawal_event',
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_event_block_number'), 'withdrawal_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_withdrawal_event_event_name'), 'withdrawal_event', ['event_name'], unique=False)
    op.create_table('zklend_collateral_debt',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('collateral', sa.JSON(), nullable=True),
    sa.Column('debt', sa.JSON(), nullable=True),
    sa.Column('deposit', sa.JSON(), nullable=True),
    sa.Column('collateral_enabled', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zklend_collateral_debt_user_id'), 'zklend_collateral_debt', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zklend_collateral_debt_user_id'), table_name='zklend_collateral_debt')
    op.drop_table('zklend_collateral_debt')
    op.drop_index(op.f('ix_withdrawal_event_event_name'), table_name='withdrawal_event')
    op.drop_index(op.f('ix_withdrawal_event_block_number'), table_name='withdrawal_event')
    op.drop_table('withdrawal_event')
    op.drop_index(op.f('ix_repayment_event_event_name'), table_name='repayment_event')
    op.drop_index(op.f('ix_repayment_event_block_number'), table_name='repayment_event')
    op.drop_table('repayment_event')
    op.drop_index(op.f('ix_orderbook_token_b'), table_name='orderbook')
    op.drop_index(op.f('ix_orderbook_token_a'), table_name='orderbook')
    op.drop_index(op.f('ix_orderbook_dex'), table_name='orderbook')
    op.drop_table('orderbook')
    op.drop_index(op.f('ix_loan_state_user'), table_name='loan_state')
    op.drop_index(op.f('ix_loan_state_timestamp'), table_name='loan_state')
    op.drop_index(op.f('ix_loan_state_block'), table_name='loan_state')
    op.drop_table('loan_state')
    op.drop_index(op.f('ix_liquidation_event_event_name'), table_name='liquidation_event')
    op.drop_index(op.f('ix_liquidation_event_block_number'), table_name='liquidation_event')
    op.drop_table('liquidation_event')
    op.drop_table('liquidable_debt')
    op.drop_index(op.f('ix_interest_rate_timestamp'), table_name='interest_rate')
    op.drop_index(op.f('ix_interest_rate_block'), table_name='interest_rate')
    op.drop_table('interest_rate')
    op.drop_index(op.f('ix_health_ratio_level_user_id'), table_name='health_ratio_level')
    op.drop_index(op.f('ix_health_ratio_level_timestamp'), table_name='health_ratio_level')
    op.drop_table('health_ratio_level')
    op.drop_index(op.f('ix_hashtack_collateral_debt_version'), table_name='hashtack_collateral_debt')
    op.drop_index(op.f('ix_hashtack_collateral_debt_user_id'), table_name='hashtack_collateral_debt')
    op.drop_table('hashtack_collateral_debt')
    op.drop_index(op.f('ix_deposit_event_event_name'), table_name='deposit_event')
    op.drop_index(op.f('ix_deposit_event_block_number'), table_name='deposit_event')
    op.drop_table('deposit_event')
    op.drop_index(op.f('ix_collateral_enabled_disabled_event_event_name'), table_name='collateral_enabled_disabled_event')
    op.drop_index(op.f('ix_collateral_enabled_disabled_event_block_number'), table_name='collateral_enabled_disabled_event')
    op.drop_table('collateral_enabled_disabled_event')
    op.drop_index(op.f('ix_borrowing_event_event_name'), table_name='borrowing_event')
    op.drop_index(op.f('ix_borrowing_event_block_number'), table_name='borrowing_event')
    op.drop_table('borrowing_event')
    op.drop_index(op.f('ix_accumulators_sync_event_event_name'), table_name='accumulators_sync_event')
    op.drop_index(op.f('ix_accumulators_sync_event_block_number'), table_name='accumulators_sync_event')
    op.drop_table('accumulators_sync_event')
    # ### end Alembic commands ###
