"""add new event models

Revision ID: aecc94d73ee6
Revises: 71a8b872296d
Create Date: 2024-10-31 12:19:17.551380

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from shared.constants import ProtocolIDs

# revision identifiers, used by Alembic.
revision: str = "aecc94d73ee6"
down_revision: Union[str, None] = "71a8b872296d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "borrowing_event_data",
        sa.Column("user", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("raw_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("face_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column(
            "protocol_id",
            sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_borrowing_event_data_block_number"),
        "borrowing_event_data",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_borrowing_event_data_event_name"),
        "borrowing_event_data",
        ["event_name"],
        unique=False,
    )
    op.create_table(
        "collateral_enabled_disabled_event_data",
        sa.Column("user", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column(
            "protocol_id",
            sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collateral_enabled_disabled_event_data_block_number"),
        "collateral_enabled_disabled_event_data",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collateral_enabled_disabled_event_data_event_name"),
        "collateral_enabled_disabled_event_data",
        ["event_name"],
        unique=False,
    )
    op.create_table(
        "deposit_event_data",
        sa.Column("user", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("face_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column(
            "protocol_id",
            sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deposit_event_data_block_number"),
        "deposit_event_data",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deposit_event_data_event_name"),
        "deposit_event_data",
        ["event_name"],
        unique=False,
    )
    op.create_table(
        "repayment_event_data",
        sa.Column("repayer", sa.String(), nullable=False),
        sa.Column("beneficiary", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("raw_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("face_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column(
            "protocol_id",
            sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repayment_event_data_block_number"),
        "repayment_event_data",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repayment_event_data_event_name"),
        "repayment_event_data",
        ["event_name"],
        unique=False,
    )
    op.create_table(
        "withdrawal_event_data",
        sa.Column("user", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("block_number", sa.Integer(), nullable=False),
        sa.Column(
            "protocol_id",
            sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_withdrawal_event_data_block_number"),
        "withdrawal_event_data",
        ["block_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_withdrawal_event_data_event_name"),
        "withdrawal_event_data",
        ["event_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_withdrawal_event_data_event_name"), table_name="withdrawal_event_data"
    )
    op.drop_index(
        op.f("ix_withdrawal_event_data_block_number"),
        table_name="withdrawal_event_data",
    )
    op.drop_table("withdrawal_event_data")
    op.drop_index(
        op.f("ix_repayment_event_data_event_name"), table_name="repayment_event_data"
    )
    op.drop_index(
        op.f("ix_repayment_event_data_block_number"), table_name="repayment_event_data"
    )
    op.drop_table("repayment_event_data")
    op.drop_index(
        op.f("ix_deposit_event_data_event_name"), table_name="deposit_event_data"
    )
    op.drop_index(
        op.f("ix_deposit_event_data_block_number"), table_name="deposit_event_data"
    )
    op.drop_table("deposit_event_data")
    op.drop_index(
        op.f("ix_collateral_enabled_disabled_event_data_event_name"),
        table_name="collateral_enabled_disabled_event_data",
    )
    op.drop_index(
        op.f("ix_collateral_enabled_disabled_event_data_block_number"),
        table_name="collateral_enabled_disabled_event_data",
    )
    op.drop_table("collateral_enabled_disabled_event_data")
    op.drop_index(
        op.f("ix_borrowing_event_data_event_name"), table_name="borrowing_event_data"
    )
    op.drop_index(
        op.f("ix_borrowing_event_data_block_number"), table_name="borrowing_event_data"
    )
    op.drop_table("borrowing_event_data")
    # ### end Alembic commands ###
