"""add DebtMintEventModel and DebtBurnEventModel tables

Revision ID: c06428099929
Revises: d3691f6e8c5a
Create Date: 2024-11-24 20:03:49.515837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06428099929'
down_revision: Union[str, None] = 'd3691f6e8c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
