"""FIx migration for new protocolID

Revision ID: e1d55c7df341
Revises: eca9b6bc75e9
Create Date: 2025-06-08 10:36:33.702924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d55c7df341'
down_revision: Union[str, None] = 'eca9b6bc75e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###