"""Add Vesu protocol support to enum constraints

Revision ID: eca9b6bc75e9
Revises: 0003f938152d
Create Date: 2025-06-04 10:21:57.261622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca9b6bc75e9'
down_revision: Union[str, None] = '0003f938152d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
