version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  backend:
    build: .
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db

  celery:
    build: .
    command: celery -A derisk_alert.celery_conf worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A derisk_alert.celery_conf beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
