[tool.poetry]
name = "derisk"
version = "0.1.0"
description = ""
authors = ["iamnovichek <rungotika@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.2"
uvicorn = "^0.29.0"
python-dotenv = "^1.0.1"
black = "^24.4.0"
isort = "^5.13.2"
sqlalchemy-utils = "^0.41.2"
email-validator = "^2.1.1"
psycopg2-binary = "^2.9.9"
sqlalchemy = "^2.0.29"
pytest = "^8.1.1"
faker = "^24.14.0"
httpx = "^0.27.0"
exrex = "^0.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
