version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build: .
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - app_network

  celery:
    build: .
    command: celery -A derisk_alert.celery_conf worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - app_network

  celery_beat:
    build: .
    command: celery -A derisk_alert.celery_conf beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - app_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/user_conf.d:ro
      - .:/app
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  db_data:
  redis_data:
