"""removed order book models'


Revision ID: 0c4f6df49ff4
Revises: f4baaac5103f
Create Date: 2024-08-15 08:52:04.029928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c4f6df49ff4"
down_revision: Union[str, None] = "f4baaac5103f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_loan_state_block", table_name="loan_state")
    op.drop_index("ix_loan_state_timestamp", table_name="loan_state")
    op.drop_index("ix_loan_state_user", table_name="loan_state")
    op.drop_table("loan_state")
    op.drop_index("ix_liquidable_debt_user", table_name="liquidable_debt")
    op.drop_table("liquidable_debt")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "liquidable_debt",
        sa.Column(
            "protocol", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("user", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_debt",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="liquidable_debt_pkey"),
    )
    op.create_index(
        "ix_liquidable_debt_user", "liquidable_debt", ["user"], unique=False
    )
    op.create_table(
        "loan_state",
        sa.Column("block", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "protocol_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("user", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "collateral",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "debt",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="loan_state_pkey"),
    )
    op.create_index("ix_loan_state_user", "loan_state", ["user"], unique=False)
    op.create_index(
        "ix_loan_state_timestamp", "loan_state", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_loan_state_block", "loan_state", ["block"], unique=False
    )
    # ### end Alembic commands ###
