"""add telegram log table

Revision ID: 6099fd3b2917
Revises: 7d6aefb54f92
Create Date: 2024-05-07 22:43:20.132142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6099fd3b2917"
down_revision: Union[str, None] = "7d6aefb54f92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("notification_data_id", sa.UUID(), nullable=True),
        sa.Column("is_succesfully", sa.Boolean(), nullable=False),
        sa.Column("message", sa.String(), server_default="", nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_data_id"],
            ["notification.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_log")
    # ### end Alembic commands ###
