"""initial migration

Revision ID: c62ca8dbda1d
Revises: 
Create Date: 2024-04-28 18:12:13.854466

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c62ca8dbda1d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_email", table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("wallet_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("telegram_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "ip_address", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "health_ration_level",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="notification_pkey"),
        sa.UniqueConstraint("telegram_id", name="notification_telegram_id_key"),
    )
    op.create_index("ix_notification_email", "notification", ["email"], unique=True)
    # ### end Alembic commands ###
