"""Missing on delete in telegram log

Revision ID: d74d2eab8acd
Revises: f4baaac5103f
Create Date: 2024-08-19 15:34:26.979221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "d74d2eab8acd"
down_revision: Union[str, None] = "f4baaac5103f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "telegram_log_notification_data_id_fkey",
        "telegram_log",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "telegram_log",
        "notification",
        ["notification_data_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "telegram_log", type_="foreignkey")
    op.create_foreign_key(
        "telegram_log_notification_data_id_fkey",
        "telegram_log",
        "notification",
        ["notification_data_id"],
        ["id"],
    )
    # ### end Alembic commands ###
