"""add vasu data

Revision ID: 0003f938152d
Revises: c53651eb145e
Create Date: 2025-06-01 19:13:45.525613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003f938152d"
down_revision: Union[str, None] = "c53651eb145e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vesu_collateral_debt",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("collateral", sa.JSON(), nullable=True),
        sa.Column("debt", sa.JSON(), nullable=True),
        sa.Column("deposit", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vesu_collateral_debt_user_id"),
        "vesu_collateral_debt",
        ["user_id"],
        unique=False,
    )
    op.drop_index(
        "ix_hashtack_collateral_debt_user_id", table_name="hashtack_collateral_debt"
    )
    op.drop_index(
        "ix_hashtack_collateral_debt_version", table_name="hashtack_collateral_debt"
    )
    op.drop_table("hashtack_collateral_debt")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashtack_collateral_debt",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("loan_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "collateral",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "debt",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("debt_category", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "original_collateral",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "borrowed_collateral",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="hashtack_collateral_debt_pkey"),
    )
    op.create_index(
        "ix_hashtack_collateral_debt_version",
        "hashtack_collateral_debt",
        ["version"],
        unique=False,
    )
    op.create_index(
        "ix_hashtack_collateral_debt_user_id",
        "hashtack_collateral_debt",
        ["user_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_vesu_collateral_debt_user_id"), table_name="vesu_collateral_debt"
    )
    op.drop_table("vesu_collateral_debt")
    # ### end Alembic commands ###
