"""new tables, vesu support

Revision ID: 227cd0abde09
Revises: 0003f938152d
Create Date: 2025-06-09 20:49:57.071381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "227cd0abde09"
down_revision: Union[str, None] = "0003f938152d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vesu_positions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("pool_id", sa.String(), nullable=True),
        sa.Column("collateral_asset", sa.String(), nullable=True),
        sa.Column("debt_asset", sa.String(), nullable=True),
        sa.Column("block_number", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vesu_positions_pool_id"), "vesu_positions", ["pool_id"], unique=False
    )
    op.create_index(
        op.f("ix_vesu_positions_user"), "vesu_positions", ["user"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vesu_positions_user"), table_name="vesu_positions")
    op.drop_index(op.f("ix_vesu_positions_pool_id"), table_name="vesu_positions")
    op.drop_table("vesu_positions")
    # ### end Alembic commands ###
