"""add constraint for loan_state'


Revision ID: 64a870953fa5
Revises: c65693d53658
Create Date: 2024-10-17 09:54:15.418485

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64a870953fa5"
down_revision: Union[str, None] = "c65693d53658"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """ Base class for collectors. """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "loan_state_protocol_id_user_key", "loan_state", ["protocol_id", "user"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """ Base classes for ORM models. """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("loan_state_protocol_id_user_key", "loan_state", type_="unique")
    # ### end Alembic commands ###
