"""health ratio model adjusted

Revision ID: efd02f93572b
Revises: 11d59882d8f6
Create Date: 2024-07-01 20:40:32.485428

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.engine import reflection

from shared.constants import ProtocolIDs

# revision identifiers, used by Alembic.
revision: str = "efd02f93572b"
down_revision: str = "509baf9251f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """ Function to apply the upgrade migrations. """

    # ### commands auto generated by Alembic - please adjust! ###

    # Reflect the current state of the table
    inspector = reflection.Inspector.from_engine(op.get_bind())
    columns = [col["name"] for col in inspector.get_columns("health_ratio_level")]

    if "protocol_id" not in columns:
        op.add_column(
            "health_ratio_level",
            sa.Column(
                "protocol_id",
                sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs),
                nullable=False,
            ),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """ Function to revert the upgrade migrations. """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("health_ratio_level", "protocol_id")
    # ### end Alembic commands ###
