"""health ratio level added

Revision ID: 11d59882d8f6
Revises: 3dc86af705d8
Create Date: 2024-06-20 21:06:43.683774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from handler_tools.constants import ProtocolIDs


# revision identifiers, used by Alembic.
revision: str = '11d59882d8f6'
down_revision: Union[str, None] = '3dc86af705d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_ratio_level',
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('value', sa.DECIMAL(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_ratio_level_timestamp'), 'health_ratio_level', ['timestamp'], unique=False)
    op.create_index(op.f('ix_health_ratio_level_user_id'), 'health_ratio_level', ['user_id'], unique=False)
    op.create_table('loan_state',
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('deposit', sa.JSON(), nullable=True),
    sa.Column('block', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs), nullable=False),
    sa.Column('collateral', sa.JSON(), nullable=True),
    sa.Column('debt', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_state_block'), 'loan_state', ['block'], unique=False)
    op.create_index(op.f('ix_loan_state_timestamp'), 'loan_state', ['timestamp'], unique=False)
    op.create_index(op.f('ix_loan_state_user'), 'loan_state', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_state_user'), table_name='loan_state')
    op.drop_index(op.f('ix_loan_state_timestamp'), table_name='loan_state')
    op.drop_index(op.f('ix_loan_state_block'), table_name='loan_state')
    op.drop_table('loan_state')
    op.drop_index(op.f('ix_health_ratio_level_user_id'), table_name='health_ratio_level')
    op.drop_index(op.f('ix_health_ratio_level_timestamp'), table_name='health_ratio_level')
    op.drop_table('health_ratio_level')
    # ### end Alembic commands ###
