"""Create loan states model

Revision ID: 1db9d85a46d3
Revises: 
Create Date: 2024-05-11 19:51:02.298804

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1db9d85a46d3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loan_states",
        sa.Column("block", sa.BigInteger(), nullable=True),
        sa.Column("timestamp", sa.BigInteger(), nullable=True),
        sa.Column("protocol", sa.String(), nullable=True),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("collateral_token", sa.String(), nullable=True),
        sa.Column("collateral_amount", sa.Float(), nullable=True),
        sa.Column("debt_token", sa.String(), nullable=True),
        sa.Column("debt_amount", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_states_block"), "loan_states", ["block"], unique=False
    )
    op.create_index(
        op.f("ix_loan_states_collateral_token"),
        "loan_states",
        ["collateral_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loan_states_debt_token"), "loan_states", ["debt_token"], unique=False
    )
    op.create_index(
        op.f("ix_loan_states_protocol"), "loan_states", ["protocol"], unique=False
    )
    op.create_index(
        op.f("ix_loan_states_timestamp"), "loan_states", ["timestamp"], unique=False
    )
    op.create_index(op.f("ix_loan_states_user"), "loan_states", ["user"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_loan_states_user"), table_name="loan_states")
    op.drop_index(op.f("ix_loan_states_timestamp"), table_name="loan_states")
    op.drop_index(op.f("ix_loan_states_protocol"), table_name="loan_states")
    op.drop_index(op.f("ix_loan_states_debt_token"), table_name="loan_states")
    op.drop_index(op.f("ix_loan_states_collateral_token"), table_name="loan_states")
    op.drop_index(op.f("ix_loan_states_block"), table_name="loan_states")
    op.drop_table("loan_states")
    # ### end Alembic commands ###
