"""add collateral debt zklend model

Revision ID: 4280b8a75614
Revises: 31430d42d46a
Create Date: 2024-07-31 09:20:15.371773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4280b8a75614"
down_revision: Union[str, None] = "31430d42d46a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zklend_collateral_debt",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("collateral", sa.JSON(), nullable=True),
        sa.Column("debt", sa.JSON(), nullable=True),
        sa.Column("deposit", sa.JSON(), nullable=True),
        sa.Column("collateral_enabled", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zklend_collateral_debt_user_id"),
        "zklend_collateral_debt",
        ["user_id"],
        unique=False,
    )
    op.drop_column("liquidable_debt", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_zklend_collateral_debt_user_id"), table_name="zklend_collateral_debt"
    )
    op.drop_table("zklend_collateral_debt")
    # ### end Alembic commands ###
