"""add health_ratio_level model

Revision ID: 509baf9251f2
Revises: d271a1dc6633
Create Date: 2024-07-07 14:39:40.075502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from handler_tools.constants import ProtocolIDs


# revision identifiers, used by Alembic.
revision: str = "509baf9251f2"
down_revision: Union[str, None] = "d271a1dc6633"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_ratio_level",
        sa.Column("timestamp", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("value", sa.DECIMAL(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "protocol_id",
            sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_ratio_level_timestamp"),
        "health_ratio_level",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_ratio_level_user_id"),
        "health_ratio_level",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_health_ratio_level_user_id"), table_name="health_ratio_level"
    )
    op.drop_index(
        op.f("ix_health_ratio_level_timestamp"), table_name="health_ratio_level"
    )
    op.drop_table("health_ratio_level")
    # ### end Alembic commands ###
