"""add interest rate model

Revision ID: 781d24d6837b
Revises: a497c48f8058
Create Date: 2024-06-04 17:20:22.686562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '781d24d6837b'
down_revision: Union[str, None] = 'a497c48f8058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orderbook_dex', table_name='orderbook')
    op.drop_index('ix_orderbook_token_a', table_name='orderbook')
    op.drop_index('ix_orderbook_token_b', table_name='orderbook')
    op.drop_table('orderbook')
    op.drop_index('ix_interest_rate_user', table_name='interest_rate')
    op.drop_column('interest_rate', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_rate', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_interest_rate_user', 'interest_rate', ['user'], unique=False)
    op.create_table('orderbook',
    sa.Column('token_a', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token_b', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('block', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('dex', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='orderbook_pkey')
    )
    op.create_index('ix_orderbook_token_b', 'orderbook', ['token_b'], unique=False)
    op.create_index('ix_orderbook_token_a', 'orderbook', ['token_a'], unique=False)
    op.create_index('ix_orderbook_dex', 'orderbook', ['dex'], unique=False)
    # ### end Alembic commands ###
