"""add hashtack collateral debt

Revision ID: 82bbb4dd7752
Revises: 70353336c9ef
Create Date: 2024-08-06 17:56:11.036936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82bbb4dd7752"
down_revision: Union[str, None] = "70353336c9ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashtack_collateral_debt",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("collateral", sa.JSON(), nullable=True),
        sa.Column("debt", sa.JSON(), nullable=True),
        sa.Column("debt_category", sa.Integer(), nullable=False),
        sa.Column("original_collateral", sa.JSON(), nullable=False),
        sa.Column("borrowed_collateral", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hashtack_collateral_debt_user_id"),
        "hashtack_collateral_debt",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_hashtack_collateral_debt_user_id"),
        table_name="hashtack_collateral_debt",
    )
    op.drop_table("hashtack_collateral_debt")
    # ### end Alembic commands ###
