"""Add column to loan states table

Revision ID: a497c48f8058
Revises: d2fa8201b04a
Create Date: 2024-05-29 08:57:03.939200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a497c48f8058'
down_revision: Union[str, None] = 'd2fa8201b04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_state', sa.Column('deposit', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_state', 'deposit')
    # ### end Alembic commands ###
