"""Current price added

Revision ID: d271a1dc6633
Revises: 593bb0a7d06b
Create Date: 2024-06-06 14:59:12.023316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd271a1dc6633'
down_revision: Union[str, None] = '593bb0a7d06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'orderbook', sa.Column('current_price', sa.DECIMAL(), nullable=False, server_default="0")
    )
    op.alter_column("orderbook", "current_price", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderbook', 'current_price')
    # ### end Alembic commands ###
