"""liquidable model adjusted

Revision ID: dcbc48c6a867
Revises: 593bb0a7d06b
Create Date: 2024-06-09 21:31:52.033413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcbc48c6a867'
down_revision: Union[str, None] = '593bb0a7d06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquidable_debt', sa.Column('collateral_token_price', sa.DECIMAL(), nullable=False))
    op.drop_column('liquidable_debt', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquidable_debt', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('liquidable_debt', 'collateral_token_price')
    # ### end Alembic commands ###
