"""add liquidable debt model

Revision ID: e4c7f75ff173
Revises: d2fa8201b04a
Create Date: 2024-06-03 17:48:10.443847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from handlers.liquidable_debt.values import LendingProtocolNames

# revision identifiers, used by Alembic.
revision: str = 'e4c7f75ff173'
down_revision: Union[str, None] = 'd2fa8201b04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidable_debt',
    sa.Column('protocol',
              sqlalchemy_utils.types.choice.ChoiceType(LendingProtocolNames), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('liquidable_debt', sa.DECIMAL(), nullable=False),
    sa.Column('health_factor', sa.DECIMAL(), nullable=False),
    sa.Column('collateral', sa.JSON(), nullable=False),
    sa.Column('risk_adjusted_collateral', sa.DECIMAL(), nullable=False),
    sa.Column('debt', sa.JSON(), nullable=False),
    sa.Column('debt_usd', sa.DECIMAL(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidable_debt_user'), 'liquidable_debt', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liquidable_debt_user'), table_name='liquidable_debt')
    op.drop_table('liquidable_debt')
    # ### end Alembic commands ###
