"""fix merge conflict

Revision ID: e813bfbd573f
Revises: 593bb0a7d06b
Create Date: 2024-07-03 16:48:38.031605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa
from handlers.liquidable_debt.values import LendingProtocolNames
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e813bfbd573f'
down_revision: Union[str, None] = '593bb0a7d06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquidable_debt', sa.Column('protocol_name', sqlalchemy_utils.types.choice.ChoiceType(LendingProtocolNames), nullable=False))
    op.add_column('liquidable_debt', sa.Column('collateral_token_price', sa.DECIMAL(), nullable=False))
    op.add_column('liquidable_debt', sa.Column('collateral_token', sa.String(), nullable=False))
    op.add_column('liquidable_debt', sa.Column('debt_token', sa.String(), nullable=False))
    op.drop_index('ix_liquidable_debt_user', table_name='liquidable_debt')
    op.drop_column('liquidable_debt', 'protocol')
    op.drop_column('liquidable_debt', 'collateral')
    op.drop_column('liquidable_debt', 'user')
    op.drop_column('liquidable_debt', 'health_factor')
    op.drop_column('liquidable_debt', 'debt')
    op.drop_column('liquidable_debt', 'debt_usd')
    op.drop_column('liquidable_debt', 'risk_adjusted_collateral')
    op.add_column('orderbook', sa.Column('current_price', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderbook', 'current_price')
    op.add_column('liquidable_debt', sa.Column('risk_adjusted_collateral', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('liquidable_debt', sa.Column('debt_usd', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('liquidable_debt', sa.Column('debt', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('liquidable_debt', sa.Column('health_factor', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('liquidable_debt', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('liquidable_debt', sa.Column('collateral', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('liquidable_debt', sa.Column('protocol', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index('ix_liquidable_debt_user', 'liquidable_debt', ['user'], unique=False)
    op.drop_column('liquidable_debt', 'debt_token')
    op.drop_column('liquidable_debt', 'collateral_token')
    op.drop_column('liquidable_debt', 'collateral_token_price')
    op.drop_column('liquidable_debt', 'protocol_name')
    # ### end Alembic commands ###
