"""health ratio model adjusted

Revision ID: efd02f93572b
Revises: 11d59882d8f6
Create Date: 2024-07-01 20:40:32.485428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from handler_tools.constants import ProtocolIDs


# revision identifiers, used by Alembic.
revision: str = 'efd02f93572b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_ratio_level', sa.Column('protocol_id', sqlalchemy_utils.types.choice.ChoiceType(ProtocolIDs), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_ratio_level', 'protocol_id')
    # ### end Alembic commands ###
