FROM python:3.11

ENV PYTHONPATH=/app

WORKDIR /app

COPY data_handler/poetry.lock data_handler/pyproject.toml /app/

RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/usr/local/ POETRY_VERSION=1.8.3 python3 -\
    && poetry config virtualenvs.create false \
    && poetry install --no-dev

COPY shared /app/shared
COPY data_handler /app/data_handler

WORKDIR /app/data_handler
